name = "sozda-site"
type = "javascript"
account_id = "e96a50452a1bfa03949db6664f4cc873"
workers_dev = true
compatibility_date = "2024-10-03"

[site]
bucket = "./dist"               # Папка с вашими статическими файлами
entry-point = "workers-site"     # Это может быть не нужно для Pages, но можно оставить
pages_build_output_dir = "./dist" # Добавьте это поле для указания директории с вашими статическими файлами
