name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Замените на вашу основную ветку, если необходимо

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Укажите версию Node.js

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Publish to Cloudflare Pages
        run: npx wrangler pages publish ./dist  # Убедитесь, что путь к вашим статическим файлам указан верно
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
